const getTranslation = (type, language) => {
  switch (type) {
    case 'food':
      return getValues(includedDecentFood, language)
    case 'nonsense':
      return getValues(includedNonsense, language)
    case 'toiletwords':
      return getValues(includedToiletWords, language)
    case 'cookingmethod':
      return getValues(cookingMethod, language)
  }
}

const getValues = (arr, language) => {
  const fallbackLanguage = 'en'

  const values = arr.find(item => item.lang === language)
  if (values) {
    return {
      language,
      values: values.values
    }
  }

  return {
    language: fallbackLanguage,
    values: arr.find(item => item.lang === fallbackLanguage).values
  }
}

const includedDecentFood = [
  {
    lang: 'no',
    values: [
      'tomat',
      'mais',
      'gulrot',
      'salat',
      'løk',
      'banan',
      'eple',
      'pære',
      'drue',
      'egg',
      'pastinakk',
      'smalahåve',
      'marsipan',
      'sennep',
      'eplejuice',
      'appelsinjuice',
      'ost',
      'brunost',
      'majones'
    ]
  },
  {
    lang: 'en',
    values: [
      'tomato',
      'corn',
      'carrot',
      'lettuce',
      'onion',
      'banana',
      'apple',
      'pear',
      'grape',
      'egg',
      'parsnip',
      'sheep\'s head',
      'marzipan',
      'mustard',
      'apple juice',
      'orange juice',
      'cheese',
      'brown cheese',
      'mayonnaise'
    ]
  },
  {
    lang: 'sv',
    values: [
      'tomat',
      'majs',
      'morot',
      'sallad',
      'lök',
      'banan',
      'äpple',
      'päron',
      'druva',
      'ägg',
      'palsternacka',
      'fårskalle',
      'marsipan',
      'senap',
      'äppeljuice',
      'apelsinjuice',
      'ost',
      'brunost',
      'majonnäs'
    ]
  },
  {
    lang: 'da',
    values: [
      'tomat',
      'majs',
      'gulerod',
      'salat',
      'løg',
      'banan',
      'æble',
      'pære',
      'drue',
      'æg',
      'pastinak',
      'fårehoved',
      'marcipan',
      'sennep',
      'æblejuice',
      'appelsinjuice',
      'ost',
      'brunost',
      'mayonnaise'
    ]
  },
  {
    lang: 'de',
    values: [
      'tomate',
      'mais',
      'karotte',
      'salat',
      'zwiebel',
      'banane',
      'apfel',
      'birne',
      'traube',
      'ei',
      'pastinake',
      'schafskopf',
      'marzipan',
      'senf',
      'apfelsaft',
      'orangensaft',
      'käse',
      'braunkäse',
      'mayonnaise'
    ]
  },
  {
    lang: 'sp',
    values: [
      'tomate',
      'maíz',
      'zanahoria',
      'lechuga',
      'cebolla',
      'plátano',
      'manzana',
      'pera',
      'uva',
      'huevo',
      'chirivía',
      'cabeza de oveja',
      'mazapán',
      'mostaza',
      'zumo de manzana',
      'zumo de naranja',
      'queso',
      'queso marrón',
      'mayonesa'
    ]
  },
  {
    lang: 'fr',
    values: [
      'tomate',
      'maïs',
      'carotte',
      'laitue',
      'oignon',
      'banane',
      'pomme',
      'poire',
      'raisin',
      'œuf',
      'panais',
      'tête de mouton',
      'massepain',
      'moutarde',
      'jus de pomme',
      'jus d\'orange',
      'fromage',
      'fromage brun',
      'mayonnaise'
    ]
  },
  {
    lang: 'it',
    values: [
      'pomodoro',
      'mais',
      'carota',
      'lattuga',
      'cipolla',
      'banana',
      'mela',
      'pera',
      'uva',
      'uovo',
      'pastinaca',
      'testa di pecora',
      'marzapane',
      'senape',
      'succo di mela',
      'succo d\'arancia',
      'formaggio',
      'formaggio marrone',
      'maionese'
    ]
  },
  {
    lang: 'nl',
    values: [
      'tomaat',
      'maïs',
      'wortel',
      'sla',
      'ui',
      'banaan',
      'appel',
      'peer',
      'druif',
      'ei',
      'pastinaak',
      'schapenkop',
      'marsepein',
      'mosterd',
      'appelsap',
      'sinaasappelsap',
      'kaas',
      'bruine kaas',
      'mayonaise'
    ]
  },
  {
    lang: 'pl',
    values: [
      'pomidor',
      'kukurydza',
      'marchew',
      'sałata',
      'cebula',
      'banan',
      'jabłko',
      'gruszka',
      'winogrono',
      'jajko',
      'pasternak',
      'głowa owcy',
      'marcepan',
      'musztarda',
      'sok jabłkowy',
      'sok pomarańczowy',
      'ser',
      'brązowy ser',
      'majonez'
    ]
  }
]

const includedNonsense = [
  {
    lang: 'no',
    values: [
      'apeloff',
      'plast',
      'hoppetævv',
      'gymsokk',
      'takpapp',
      'juleduk',
      'slimgugge',
      'mammut',
      'kvæleslange',
      'skapdør',
      'knekt hale',
      'plaster',
      'slimpudding',
      'gulvbelegg',
      'reinsdyrføtter',
      'paddevorte',
      'slim',
      'skrutrekker',
      'svette',
      'dovendyr',
      'hest',
      'hatt',
      'havfrue',
      'juletre'
    ]
  },
  {
    lang: 'en',
    values: [
      'ape bread',
      'plastic',
      'jump rope',
      'gym sock',
      'roof felt',
      'christmas cloth',
      'slimy goo',
      'mammoth',
      'constrictor snake',
      'cabinet door',
      'broken tail',
      'band-aid',
      'slime pudding',
      'flooring',
      'reindeer feet',
      'toad wart',
      'slime',
      'screwdriver',
      'sweat',
      'sloth',
      'horse',
      'hat',
      'mermaid',
      'christmas tree'
    ]
  },
  {
    lang: 'sv',
    values: [
      'apbröd',
      'plast',
      'hopprep',
      'gymsocka',
      'takpapp',
      'julduk',
      'slimig gegga',
      'mammut',
      'stryporm',
      'skåpdörr',
      'bruten svans',
      'plåster',
      'slem-pudding',
      'golvbeläggning',
      'renfötter',
      'paddvårta',
      'slem',
      'skruvmejsel',
      'svett',
      'sengångare',
      'häst',
      'hatt',
      'sjöjungfru',
      'julgran'
    ]
  },
  {
    lang: 'da',
    values: [
      'abe-brød',
      'plastik',
      'sjippetov',
      'gymsok',
      'tagpap',
      'juledug',
      'slimet gup',
      'mammut',
      'kvælerslange',
      'skabslåge',
      'knækket hale',
      'plaster',
      'slimpudding',
      'gulvbelægning',
      'rensdyrfødder',
      'paddevorte',
      'slim',
      'skruetrækker',
      'sved',
      'dovendyr',
      'hest',
      'hat',
      'havfrue',
      'juletræ'
    ]
  },
  {
    lang: 'de',
    values: [
      'affenbrot',
      'plastik',
      'springseil',
      'turnsocke',
      'dachpappe',
      'weihnachtstischdecke',
      'schleimige masse',
      'mammut',
      'würgeschlange',
      'schranktür',
      'gebrochener schwanz',
      'pflaster',
      'schleimpudding',
      'bodenbelag',
      'rentierfüße',
      'krötenwarze',
      'schleim',
      'schraubenzieher',
      'schweiß',
      'faultier',
      'pferd',
      'hut',
      'meerjungfrau',
      'weihnachtsbaum'
    ]
  },
  {
    lang: 'sp',
    values: [
      'pan de mono',
      'plástico',
      'cuerda para saltar',
      'calcetín de gimnasio',
      'fieltro para tejados',
      'mantel navideño',
      'masa viscosa',
      'mamut',
      'serpiente constrictora',
      'puerta del armario',
      'cola rota',
      'tirita',
      'pudín de moco',
      'revestimiento de suelo',
      'pies de reno',
      'verruga de sapo',
      'moco',
      'destornillador',
      'sudor',
      'perezoso',
      'caballo',
      'sombrero',
      'sirena',
      'árbol de navidad'
    ]
  },
  {
    lang: 'fr',
    values: [
      'pain de singe',
      'plastique',
      'corde à sauter',
      'chaussette de gym',
      'feutre de toit',
      'nappe de Noël',
      'glaire visqueuse',
      'mammouth',
      'serpent constricteur',
      'porte d\'armoire',
      'queue cassée',
      'pansement',
      'pudding de slime',
      'revêtement de sol',
      'pieds de renne',
      'verrue de crapaud',
      'bave',
      'tournevis',
      'sueur',
      'paresseux',
      'cheval',
      'chapeau',
      'sirène',
      'sapin de Noël'
    ]
  },
  {
    lang: 'it',
    values: [
      'pane di scimmia',
      'plastica',
      'corda per saltare',
      'calzino da palestra',
      'feltro per tetti',
      'tovaglia natalizia',
      'melma viscosa',
      'mammut',
      'serpente costrittore',
      'porta dell\'armadio',
      'coda rotta',
      'cerotto',
      'budino di muco',
      'pavimentazione',
      'zampe di renna',
      'verruca di rospo',
      'muco',
      'cacciavite',
      'sudore',
      'bradipo',
      'cavallo',
      'cappello',
      'sirena',
      'albero di Natale'
    ]
  },
  {
    lang: 'nl',
    values: [
      'apenbrood',
      'plastic',
      'springtouw',
      'gymsok',
      'dakleer',
      'kerstkleed',
      'slijmerige massa',
      'mammoet',
      'wurgslang',
      'kastdeur',
      'gebroken staart',
      'pleister',
      'slijmpudding',
      'vloerbedekking',
      'rendierenvoeten',
      'padtenen',
      'slijm',
      'schroevendraaier',
      'zweet',
      'luiaard',
      'paard',
      'hoed',
      'zeemeermin',
      'kerstboom'
    ]
  },
  {
    lang: 'pl',
    values: [
      'chleb małpy',
      'plastik',
      'skakanka',
      'skarpeta na siłownię',
      'papa dachowa',
      'obrus świąteczny',
      'śluzowata masa',
      'mamut',
      'wąż dusiciel',
      'drzwi szafy',
      'złamany ogon',
      'plaster',
      'pudding ze śluzu',
      'pokrycie podłogi',
      'stopy renifera',
      'brodawka ropucha',
      'śluz',
      'śrubokręt',
      'pot',
      'leniwiec',
      'koń',
      'kapelusz',
      'syrena',
      'choinka'
    ]
  }
]

const includedToiletWords = [
  {
    lang: 'no',
    values: [
      'buse',
      'truse',
      'bæsjebleie',
      'bæsj',
      'gulp',
      'snørr',
      'rumpeklut',
      'BH',
      'prump',
      'bleie',
      'fis',
      'smyger',
      'rumpe'
    ]
  },
  {
    lang: 'en',
    values: [
      'booger',
      'underpants',
      'poopy diaper',
      'poop',
      'vomit',
      'snot',
      'butt wipe',
      'bra',
      'fart',
      'diaper',
      'toot',
      'silent fart',
      'butt'
    ]
  },
  {
    lang: 'sv',
    values: [
      'snor',
      'kalsong',
      'bajsblöja',
      'bajs',
      'kräks',
      'snor',
      'rumpduk',
      'bh',
      'fjärt',
      'blöja',
      'fis',
      'smygfis',
      'rumpa'
    ]
  },
  {
    lang: 'da',
    values: [
      'bussemand',
      'underbukser',
      'lorteble',
      'lort',
      'bræk',
      'snot',
      'numseklud',
      'bh',
      'prut',
      'ble',
      'prut',
      'stille prut',
      'numse'
    ]
  },
  {
    lang: 'de',
    values: [
      'popel',
      'unterhose',
      'kackwindel',
      'kacke',
      'kotze',
      'rotz',
      'popotuch',
      'bh',
      'furz',
      'windel',
      'pups',
      'schleichpups',
      'hintern'
    ]
  },
  {
    lang: 'sp',
    values: [
      'moco',
      'calzoncillo',
      'pañal de caca',
      'caca',
      'vómito',
      'moco',
      'toallita para el trasero',
      'sujetador',
      'pedo',
      'pañal',
      'pedo',
      'pedo silencioso',
      'culo'
    ]
  },
  {
    lang: 'fr',
    values: [
      'morve',
      'culotte',
      'couche sale',
      'caca',
      'vomit',
      'morve',
      'lingette pour fesses',
      'soutien-gorge',
      'pet',
      'couche',
      'prout',
      'pet silencieux',
      'fesses'
    ]
  },
  {
    lang: 'it',
    values: [
      'caccola',
      'mutande',
      'pannolino sporco',
      'cacca',
      'vomito',
      'muco',
      'salvietta per il sedere',
      'reggiseno',
      'peto',
      'pannolino',
      'peto',
      'peto silenzioso',
      'sedere'
    ]
  },
  {
    lang: 'nl',
    values: [
      'snotje',
      'onderbroek',
      'poepluier',
      'poep',
      'braaksel',
      'snot',
      'kontdoek',
      'bh',
      'scheet',
      'luier',
      'scheetje',
      'stille scheet',
      'kont'
    ]
  },
  {
    lang: 'pl',
    values: [
      'glut',
      'majtki',
      'brudna pielucha',
      'kupa',
      'wymiociny',
      'smark',
      'ściereczka na tyłek',
      'biustonosz',
      'pierdnięcie',
      'pielucha',
      'bąk',
      'cichy bąk',
      'pupa'
    ]
  }
]

const cookingMethod = [
  {
    lang: 'no',
    values: [
      'gratinert',
      'stekt',
      'kokt',
      'frossen',
      'rista',
      'grilla',
      'barbert',
      'svidd',
      'rå',
      'sinna',
      'råtten',
      'svett',
      'tørka',
      'salta',
      'frityrstekt',
      'dypfryst',
      'boblete',
      'ferdigspist',
      'halvspist',
      'tvinna',
      'påkjørt',
      'sprengt',
      'kastet',
      'vrengt',
      'oppgulpa',
      'nedgravd'
    ]
  },
  {
    lang: 'en',
    values: [
      'gratinated',
      'fried',
      'boiled',
      'frozen',
      'toasted',
      'grilled',
      'shaved',
      'burnt',
      'raw',
      'angry',
      'rotten',
      'sweaty',
      'dried',
      'salted',
      'deep-fried',
      'deep frozen',
      'bubbly',
      'pre-eaten',
      'half-eaten',
      'twisted',
      'run over',
      'exploded',
      'thrown',
      'inside-out',
      'vomited',
      'buried'
    ]
  },
  {
    lang: 'sv',
    values: [
      'gratinerad',
      'stekt',
      'kokt',
      'fryst',
      'rostad',
      'grillad',
      'rakad',
      'bränd',
      'rå',
      'arg',
      'rutten',
      'svettig',
      'torkad',
      'saltad',
      'friterad',
      'djupfryst',
      'bubblig',
      'föreäten',
      'halvätad',
      'vriden',
      'överrullad',
      'exploderad',
      'kastad',
      'ut och in',
      'uppkräkt',
      'begravd'
    ]
  },
  {
    lang: 'da',
    values: [
      'gratineret',
      'stegt',
      'kogt',
      'frossen',
      'ristet',
      'grillet',
      'barberet',
      'brændt',
      'rå',
      'vred',
      'rådden',
      'svedig',
      'tørret',
      'saltet',
      'friturestegt',
      'dybfrossen',
      'boblende',
      'for-spist',
      'halvspist',
      'vridet',
      'overkørt',
      'sprængt',
      'kastet',
      'vendt på vrangen',
      'opkastet',
      'nedgravet'
    ]
  },
  {
    lang: 'de',
    values: [
      'gratiniert',
      'gebraten',
      'gekocht',
      'gefroren',
      'getoastet',
      'gegrillt',
      'rasiert',
      'verbrannt',
      'roh',
      'wütend',
      'verrottet',
      'verschwitzt',
      'getrocknet',
      'gesalzen',
      'frittiert',
      'tiefgefroren',
      'sprudelnd',
      'vorab gegessen',
      'halb gegessen',
      'verdreht',
      'überfahren',
      'explodiert',
      'geworfen',
      'umgedreht',
      'erbrochen',
      'vergraben'
    ]
  },
  {
    lang: 'sp',
    values: [
      'gratinar',
      'frito',
      'hervido',
      'congelado',
      'tostado',
      'asado',
      'afeitado',
      'quemado',
      'crudo',
      'enfadado',
      'podrido',
      'sudoroso',
      'seco',
      'salado',
      'frito en sartén',
      'ultracongelado',
      'burbujeante',
      'precomido',
      'medio comido',
      'torcido',
      'atropellado',
      'explotado',
      'tirado',
      'al revés',
      'vomitado',
      'enterrado'
    ]
  },
  {
    lang: 'fr',
    values: [
      'gratiné',
      'frit',
      'bouilli',
      'congelé',
      'grillé',
      'barbecue',
      'rasé',
      'brûlé',
      'cru',
      'fâché',
      'pourri',
      'en sueur',
      'séché',
      'salé',
      'friture',
      'ultra congelé',
      'pétillant',
      'pré-mangé',
      'demi-mangé',
      'tordu',
      'écrasé',
      'explosé',
      'jeté',
      'à l\'envers',
      'vomit',
      'enterré'
    ]
  },
  {
    lang: 'it',
    values: [
      'gratinato',
      'fritto',
      'bollito',
      'congelato',
      'tostato',
      'grigliato',
      'rasato',
      'bruciato',
      'crudo',
      'arrabbiato',
      'marcio',
      'sudato',
      'essiccato',
      'salato',
      'fritto',
      'surgelato',
      'frizzante',
      'mangiato',
      'mezzo mangiato',
      'attorcigliato',
      'investito',
      'esploso',
      'gettato',
      'rivoltato',
      'vomitato',
      'sepolto'
    ]
  },
  {
    lang: 'nl',
    values: [
      'gegratineerd',
      'gebakken',
      'gekookt',
      'bevroren',
      'geroosterd',
      'gegrild',
      'geschoren',
      'verbrand',
      'rauw',
      'boos',
      'rot',
      'bezweet',
      'gedroogd',
      'gezouten',
      'gefrituurd',
      'diepvries',
      'bubbels',
      'vooraf gegeten',
      'half gegeten',
      'gedraaid',
      'overreden',
      'ontploft',
      'gegooid',
      'binnenstebuiten',
      'uitgebraakt',
      'begraven'
    ]
  },
  {
    lang: 'pl',
    values: [
      'zapiekany',
      'smażony',
      'gotowany',
      'mrożony',
      'tostowany',
      'grillowany',
      'ogolony',
      'spalony',
      'surowy',
      'wściekły',
      'zgniły',
      'spocony',
      'suszony',
      'solony',
      'smażony w głębokim tłuszczu',
      'głęboko mrożony',
      'bąbelkowy',
      'wstępnie zjedzony',
      'pół-zjedzony',
      'skręcony',
      'przejechany',
      'eksplodowany',
      'rzucony',
      'na lewą stronę',
      'wymiotowany',
      'zakopany'
    ]
  }
]

module.exports = {
  getTranslation
}
